version: "3.3"
services:
  hello:
    build: .
    image: node-hello:tst
    ports:
      - published: 8080
        target: 8080
        mode: ingress
    environment:
      - PORT=8080
    deploy:
      replicas: 1
